/* eslint-disable jsdoc/require-jsdoc */

// Parameters are generated by a reference script https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/generate_parameters_grain.sage
// Used like so: sage generate_parameters_grain.sage 1 0 254 2 8 56 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001

// Using recommended parameters from whitepaper https://eprint.iacr.org/2019/458.pdf (table 2, table 8)
// Generated by https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/calc_round_numbers.py
// And rounded up to nearest integer that divides by t

// Optimization is taken from https://github.com/filecoin-project/neptune

// taken from iden3/circomlib: reduced and modified

import assert from 'assert'

import type { FieldInput } from './bn254'
import { Fr } from './bn254'
import poseidonConstants from './poseidon_constants_opt'

export function unsringifyConstants (F: typeof Fr, o: typeof poseidonConstants): any {
  if (typeof o === 'string' && /^[0-9]+$/.test(o)) {
    return F.e(o)
  } else if (typeof o === 'string' && /^0x[0-9a-fA-F]+$/.test(o)) {
    return F.e(o)
  } else if (Array.isArray(o)) {
    return o.map(unsringifyConstants.bind(null, F))
  } else if (typeof o === 'object') {
    if (o === null) return null
    const res: any = {}
    const keys = Object.keys(o)
    keys.forEach((k) => {
      // @ts-ignore - TODO: typefix
      res[k] = unsringifyConstants(F, o[k])
    })
    return res
  } else {
    return o
  }
}

export default function buildPoseidon () {
  const F = Fr

  const opt = unsringifyConstants(F, poseidonConstants)

  const N_ROUNDS_F = 8
  const N_ROUNDS_P = [
    56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68,
  ]

  const pow5 = (a: bigint) => F.mul(a, F.square(F.square(a)))

  function poseidon (inputs: FieldInput[], initState: any, nOut: any) {
    assert(inputs.length > 0)
    assert(inputs.length <= N_ROUNDS_P.length)
    if (initState) {
      initState = F.e(initState)
    } else {
      initState = F.zero
    }
    nOut = nOut || 1
    // console.log('initState old', initState)

    const t = inputs.length + 1
    const nRoundsF = N_ROUNDS_F
    const nRoundsP = N_ROUNDS_P[t - 2]
    const C = opt.C[t - 2]
    const S = opt.S[t - 2]
    const M = opt.M[t - 2]
    const P = opt.P[t - 2]
    // console.log('inputs', inputs)
    let state = [initState, ...inputs.map((a) => F.e(a))]
    // console.log('initial state og', state)
    state = state.map((a, i) => F.add(a, C[i]))
    // console.log('afterstate', state)

    for (let r = 0; r < nRoundsF / 2 - 1; r++) {
      state = state.map((a) => pow5(a))
      // console.log('po5 og', state)
      state = state.map((a, i) => F.add(a, C[(r + 1) * t + i]))
      state = state.map((_, i) =>
        state.reduce((acc, a, j) => F.add(acc, F.mul(M[j][i], a)), F.zero)
      )
    }
    // console.log('after first og', state)

    state = state.map((a) => pow5(a))
    state = state.map((a, i) => F.add(a, C[(nRoundsF / 2 - 1 + 1) * t + i]))
    state = state.map((_, i) =>
      state.reduce((acc, a, j) => F.add(acc, F.mul(P[j][i], a)), F.zero)
    )
    // console.log('after first og2', state)

    for (let r = 0; r < nRoundsP!; r++) {
      state[0] = pow5(state[0])
      state[0] = F.add(state[0], C[(nRoundsF / 2 + 1) * t + r])
      const s0 = state.reduce((acc, a, j) => {
        return F.add(acc, F.mul(S[(t * 2 - 1) * r + j], a))
      }, F.zero)
      for (let k = 1; k < t; k++) {
        state[k] = F.add(
          state[k],
          F.mul(state[0], S[(t * 2 - 1) * r + t + k - 1])
        )
      }
      state[0] = s0
    }
    // console.log('after first og23', state[0])
    for (let r = 0; r < nRoundsF / 2 - 1; r++) {
      state = state.map((a) => pow5(a))
      state = state.map((a, i) =>
        F.add(a, C[(nRoundsF / 2 + 1) * t + nRoundsP! + r * t + i])
      )
      state = state.map((_, i) =>
        state.reduce((acc, a, j) => F.add(acc, F.mul(M[j][i], a)), F.zero)
      )
    }
    // console.log('after first og233', state)

    state = state.map((a) => pow5(a))
    state = state.map((_, i) =>
      state.reduce((acc, a, j) => F.add(acc, F.mul(M[j][i], a)), F.zero)
    )

    if (nOut === 1) {
      return state[0]
    } else {
      return state.slice(0, nOut)
    }
  }

  poseidon.F = F
  return poseidon
}
