// Parameters are generated by a reference script https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/generate_parameters_grain.sage
// Used like so: sage generate_parameters_grain.sage 1 0 254 2 8 56 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001

// Using recommended parameters from whitepaper https://eprint.iacr.org/2019/458.pdf (table 2, table 8)
// Generated by https://extgit.iaik.tugraz.at/krypto/hadeshash/-/blob/master/code/calc_round_numbers.py
// And rounded up to nearest integer that divides by t

// Optimization is taken from https://github.com/filecoin-project/neptune

// taken from iden3/circomlib: reduced and modified

import assert from 'assert'

import type { FieldInput } from './bn254'
import { Fr } from './bn254'
import poseidonConstants from './poseidon_constants_opt'

/**
 * Recursively converts stringified constants back to field elements using the provided field constructor.
 * Handles numeric strings, hexadecimal strings, arrays, and nested objects containing such values.
 * @param F - The field constructor (typically Fr) used to create field elements
 * @param o - The object, array, or string to unstringify, expected to be of poseidonConstants type
 * @returns The unstringified object with string constants converted to field elements
 * @example
 * ```typescript
 * const result = unsringifyConstants(Fr, "123");
 * // Returns Fr.e("123")
 * ```
 * @example
 * ```typescript
 * const result = unsringifyConstants(Fr, ["123", "0x456"]);
 * // Returns [Fr.e("123"), Fr.e("0x456")]
 * ```
 * @example
 * ```typescript
 * const result = unsringifyConstants(Fr, { key: "789" });
 * // Returns { key: Fr.e("789") }
 * ```
 */
export function unsringifyConstants (F: typeof Fr, o: typeof poseidonConstants): any {
  if (typeof o === 'string' && /^[0-9]+$/.test(o)) {
    return F.e(o)
  } else if (typeof o === 'string' && /^0x[0-9a-fA-F]+$/.test(o)) {
    return F.e(o)
  } else if (Array.isArray(o)) {
    return o.map(unsringifyConstants.bind(null, F))
  } else if (typeof o === 'object') {
    if (o === null) return null
    const res: any = {}
    const keys = Object.keys(o)
    keys.forEach((k) => {
      // @ts-ignore - TODO: typefix
      res[k] = unsringifyConstants(F, o[k])
    })
    return res
  } else {
    return o
  }
}

/**
 * Builds and returns an optimized Poseidon hash function implementation.
 * Poseidon is a cryptographic hash function designed for zero-knowledge proof systems,
 * offering efficient performance in algebraic circuits. This implementation uses
 * precomputed constants and optimized round functions for maximum efficiency.
 * @returns A Poseidon hash function that accepts field inputs and returns hash output(s)
 * @example
 * ```typescript
 * const poseidon = buildPoseidon();
 * const hash = poseidon([1n, 2n, 3n]); // Hash 3 inputs, return single output
 * const multiHash = poseidon([1n, 2n], null, 2); // Return 2 outputs
 * const withInitState = poseidon([1n], 5n, 1); // Use custom initial state
 * ```
 */
export default function buildPoseidon () {
  const F = Fr

  const opt = unsringifyConstants(F, poseidonConstants)

  const N_ROUNDS_F = 8
  const N_ROUNDS_P = [
    56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68,
  ]

  /**
   * Computes the fifth power of a field element by multiplying it with its fourth power (square of square).
   * @param a - The field element to raise to the fifth power
   * @returns The fifth power of the input field element
   * @example ```typescript
   * const result = pow5(5n); // Returns 5^5 = 3125n in the field
   * ```
   * @example ```typescript
   * const fieldElement = 7n;
   * const fifthPower = pow5(fieldElement); // Computes 7^5 efficiently
   * ```
   */
  const pow5 = (a: bigint) => F.mul(a, F.square(F.square(a)))

  /**
   * Computes the Poseidon hash function, a cryptographic hash designed for zero-knowledge proof systems.
   * @param inputs - Array of field elements to be hashed
   * @param initState - Initial state for the hash computation, defaults to zero field element
   * @param nOut - Number of output elements to return, defaults to 1
   * @returns Single field element if nOut is 1, otherwise array of field elements
   * @example
   * ```typescript
   * // Hash a single input
   * const hash = poseidon([F.e(42)]);
   * // Hash multiple inputs with custom output length
   * const multiHash = poseidon([F.e(1), F.e(2), F.e(3)], null, 2);
   * // Hash with initial state
   * const stateHash = poseidon([F.e(100)], F.e(200));
   * ```
   */
  function poseidon (inputs: (FieldInput | Uint8Array)[], initState: any, nOut: any) {
    assert(inputs.length > 0)
    assert(inputs.length <= N_ROUNDS_P.length)
    if (initState) {
      initState = F.e(initState)
    } else {
      initState = F.zero
    }
    nOut = nOut || 1

    const t = inputs.length + 1
    const nRoundsF = N_ROUNDS_F
    const nRoundsP = N_ROUNDS_P[t - 2]
    const C = opt.C[t - 2]
    const S = opt.S[t - 2]
    const M = opt.M[t - 2]
    const P = opt.P[t - 2]
    let state = [initState, ...inputs.map((a) => F.e(a))]
    state = state.map((a, i) => F.add(a, C[i]))

    for (let r = 0; r < nRoundsF / 2 - 1; r++) {
      state = state.map((a) => pow5(a))
      state = state.map((a, i) => F.add(a, C[(r + 1) * t + i]))
      state = state.map((_, i) =>
        state.reduce((acc, a, j) => F.add(acc, F.mul(M[j][i], a)), F.zero)
      )
    }

    state = state.map((a) => pow5(a))
    state = state.map((a, i) => F.add(a, C[(nRoundsF / 2 - 1 + 1) * t + i]))
    state = state.map((_, i) =>
      state.reduce((acc, a, j) => F.add(acc, F.mul(P[j][i], a)), F.zero)
    )

    for (let r = 0; r < nRoundsP!; r++) {
      state[0] = pow5(state[0])
      state[0] = F.add(state[0], C[(nRoundsF / 2 + 1) * t + r])
      const s0 = state.reduce((acc, a, j) => {
        return F.add(acc, F.mul(S[(t * 2 - 1) * r + j], a))
      }, F.zero)
      for (let k = 1; k < t; k++) {
        state[k] = F.add(
          state[k],
          F.mul(state[0], S[(t * 2 - 1) * r + t + k - 1])
        )
      }
      state[0] = s0
    }
    for (let r = 0; r < nRoundsF / 2 - 1; r++) {
      state = state.map((a) => pow5(a))
      state = state.map((a, i) =>
        F.add(a, C[(nRoundsF / 2 + 1) * t + nRoundsP! + r * t + i])
      )
      state = state.map((_, i) =>
        state.reduce((acc, a, j) => F.add(acc, F.mul(M[j][i], a)), F.zero)
      )
    }

    state = state.map((a) => pow5(a))
    state = state.map((_, i) =>
      state.reduce((acc, a, j) => F.add(acc, F.mul(M[j][i], a)), F.zero)
    )

    if (nOut === 1) {
      return state[0]
    } else {
      return state.slice(0, nOut)
    }
  }

  poseidon.F = F
  return poseidon
}
